[files]
extend-exclude = [
    "database",
    "**/tests/**",
    "**/messages/**"
]

[default.extend-words]
selectin = "selectin"
FPT = "FPT"
OT = "OT"
ot = "ot"
Tham = "Tham"
tham = "tham"
Nam = "Nam"
