services:
  backend:
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /app/backend/logs:uid=1000,gid=1000
    security_opt:
      - no-new-privileges:true
    deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 1G
          reservations:
            memory: 256M


  frontend:
    restart: always
    ports:
      - "3000:3000"
    deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 1G
          reservations:
            memory: 256M

  db:
    restart: always
    deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 2G
          reservations:
            memory: 512M
