services:
  backend:
    restart: "no"
    ports:
      - "8081:8000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./database:/app/backend/database
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  backend-init:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./database:/app/backend/database
      - ./database/alembic.ini:/app/backend/alembic.ini
    command: >
      sh -c "alembic -c database/alembic.ini upgrade head && python app/fixtures/initial_data.py"

  frontend:
    restart: "no"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dependencies
      args:
        - NEXTJS_API_URL=http://localhost:8081/api/v1
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8081/api/v1
    volumes:
      - frontend_next:/app/.next
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/next.config.mjs:/app/next.config.mjs
      - ./frontend/jsconfig.json:/app/jsconfig.json
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
    command: npm run dev

  nginx:
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    restart: unless-stopped
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    image: adminer:5.5.0-standalone@sha256:a1e730bf95a18f1d7c38b409ab58a39d57d07bdb090614b81f5c7b37c6021b96
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    networks:
      - backend
      - frontend

  rabbitmq:
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker-default:
    restart: "no"
    build:
      context: .
      dockerfile: celery/Dockerfile
    volumes:
      - ./backend/app:/app/backend/app
      - ./celery:/app/celery
      - ./database:/app/backend/database
      - ./scripts:/app/scripts

  celery-worker-crawler:
    restart: "no"
    build:
      context: .
      dockerfile: celery/Dockerfile
    volumes:
      - ./backend/app:/app/backend/app
      - ./celery:/app/celery
      - ./database:/app/backend/database
      - ./scripts:/app/scripts

  celery-beat:
    restart: "no"
    build:
      context: .
      dockerfile: celery/Dockerfile
    volumes:
      - ./backend/app:/app/backend/app
      - ./celery:/app/celery
      - ./scripts:/app/scripts

  redis:
    restart: "no"

volumes:
  frontend_next:
