sonar.projectKey=JuniorThanhBQ_AI-IT-Job-Market-Consultant
sonar.organization=juniorthanhb

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/.venv/**,**/dist/**,**/.next/**,**/migrations/**,**/*.spec.*

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
