from app.core.config import settings

DATABASE_URL = str(settings.database.ASYNC_SQLALCHEMY_DATABASE_URI)
REDIS_URL = settings.redis.REDIS_URL


MAX_REQUESTS_PER_CRAWL = settings.crawler.CRAWLER_MAX_REQUESTS_PER_CRAWL
MAX_REQUEST_RETRIES = settings.crawler.CRAWLER_MAX_REQUEST_RETRIES
MAX_CONCURRENCY = settings.crawler.CRAWLER_MAX_CONCURRENCY
SITE_CRAWL_TIMEOUT_SECONDS = settings.crawler.SITE_CRAWL_TIMEOUT_SECONDS
REQUEST_HANDLER_TIMEOUT_SECONDS = (
    settings.crawler.CRAWLER_REQUEST_HANDLER_TIMEOUT_SECONDS
)
MIN_DELAY_SECONDS = settings.crawler.CRAWLER_MIN_DELAY_SECONDS
MAX_DELAY_SECONDS = settings.crawler.CRAWLER_MAX_DELAY_SECONDS

BROWSER_TYPE = settings.crawler.CRAWLER_BROWSER_TYPE
HEADLESS = settings.crawler.CRAWLER_HEADLESS
