from app.core.config import settings

DATABASE_URL = str(settings.ASYNC_SQLALCHEMY_DATABASE_URI)
REDIS_URL = settings.REDIS_URL


MAX_REQUESTS_PER_CRAWL = settings.CRAWLER_MAX_REQUESTS_PER_CRAWL
MAX_REQUEST_RETRIES = settings.CRAWLER_MAX_REQUEST_RETRIES
MAX_CONCURRENCY = settings.CRAWLER_MAX_CONCURRENCY
SITE_CRAWL_TIMEOUT_SECONDS = settings.SITE_CRAWL_TIMEOUT_SECONDS
REQUEST_HANDLER_TIMEOUT_SECONDS = settings.CRAWLER_REQUEST_HANDLER_TIMEOUT_SECONDS
MIN_DELAY_SECONDS = settings.CRAWLER_MIN_DELAY_SECONDS
MAX_DELAY_SECONDS = settings.CRAWLER_MAX_DELAY_SECONDS

BROWSER_TYPE = settings.CRAWLER_BROWSER_TYPE
HEADLESS = settings.CRAWLER_HEADLESS
