"""rework database model version 2.0

Revision ID: 1023ca41535d
Revises: 2e2f51650d34
Create Date: 2026-07-31 10:39:56.125233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""rework database model version 2.0

Revision ID: 1023ca41535d
Revises: 2e2f51650d34
Create Date: 2026-07-31 10:39:56.125233

"""


# revision identifiers, used by Alembic.
revision: str = "1023ca41535d"
down_revision: Union[str, Sequence[str], None] = "2e2f51650d34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create countryenum and crawlwebsite enum types
    country_enum = postgresql.ENUM(
        "VIETNAM",
        "INDIA",
        "CHINA",
        "JAPAN",
        "SOUTH_KOREA",
        "SINGAPORE",
        "TAIWAN",
        "UNITED_STATES",
        "CANADA",
        "UNITED_KINGDOM",
        "GERMANY",
        "NETHERLANDS",
        "SWEDEN",
        "FRANCE",
        "IRELAND",
        "POLAND",
        "AUSTRALIA",
        "NEW_ZEALAND",
        name="countryenum",
    )
    country_enum.create(op.get_bind(), checkfirst=True)

    crawl_website_enum = postgresql.ENUM(
        "ITVIEC", "TOPDEV", "ITJOBS", "VIETNAMWORKS", "FPTJOBS", name="crawlwebsite"
    )
    crawl_website_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("github_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_github_id"), "user", ["github_id"], unique=True)
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=True)
    op.create_table(
        "company_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(
                sa.JSON(), "sqlite"
            ),
            nullable=True,
        ),
        sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_used", sa.Float(), nullable=True),
        sa.Column("latency", sa.Float(), nullable=True),
        sa.Column("log", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_company_embeddings_embedding_hnsw",
        "company_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_company_embeddings_company_id"),
        "company_embeddings",
        ["company_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_company_embeddings_embedding_model"),
        "company_embeddings",
        ["embedding_model"],
        unique=False,
    )
    op.create_table(
        "consultant_histories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("user_input", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "input_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(
                sa.JSON(), "sqlite"
            ),
            nullable=True,
        ),
        sa.Column("output", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "consultant_mode",
            sa.Enum(
                "MARKET_ANALYSIS",
                "PERSONAL_STANDARD_EVALUATION",
                "JOB_RECOMMEND",
                "DEEP_ANALYSIS_EVALUATION",
                name="consultantmode",
            ),
            nullable=False,
        ),
        sa.Column("request_log", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response_log", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_used", sa.Float(), nullable=True),
        sa.Column("latency", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consultant_histories_consultant_mode"),
        "consultant_histories",
        ["consultant_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consultant_histories_user_id"),
        "consultant_histories",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "consultee_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("biography", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vector_context", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consultee_profiles_user_id"),
        "consultee_profiles",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "consultee_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(
                sa.JSON(), "sqlite"
            ),
            nullable=True,
        ),
        sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_used", sa.Float(), nullable=True),
        sa.Column("latency", sa.Float(), nullable=True),
        sa.Column("log", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["consultee_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_consultee_embeddings_embedding_hnsw",
        "consultee_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_consultee_embeddings_embedding_model"),
        "consultee_embeddings",
        ["embedding_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consultee_embeddings_profile_id"),
        "consultee_embeddings",
        ["profile_id"],
        unique=True,
    )
    op.create_table(
        "curriculum_vitaes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "general_information", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("job_position", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("education", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "certifications",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "skills",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("structure_illogical", sa.Boolean(), nullable=False),
        sa.Column("bad_text_recognition", sa.Boolean(), nullable=False),
        sa.Column("exceed_page_limit", sa.Boolean(), nullable=False),
        sa.Column("using_cv_mode", sa.Boolean(), nullable=False),
        sa.Column("attachment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["consultee_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curriculum_vitaes_profile_id"),
        "curriculum_vitaes",
        ["profile_id"],
        unique=True,
    )
    op.create_table(
        "job_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(
                sa.JSON(), "sqlite"
            ),
            nullable=True,
        ),
        sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_used", sa.Float(), nullable=True),
        sa.Column("latency", sa.Float(), nullable=True),
        sa.Column("log", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_job_embeddings_embedding_hnsw",
        "job_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_job_embeddings_embedding_model"),
        "job_embeddings",
        ["embedding_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_embeddings_job_id"), "job_embeddings", ["job_id"], unique=True
    )
    op.create_table(
        "curriculum_vitae_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cv_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "tech_stacks",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_size", sa.Integer(), nullable=False),
        sa.Column(
            "responsibilities",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["cv_id"], ["curriculum_vitaes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curriculum_vitae_projects_cv_id"),
        "curriculum_vitae_projects",
        ["cv_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_company_benefits_company_id"), table_name="company_benefits")
    op.drop_table("company_benefits")
    op.add_column(
        "companies",
        sa.Column(
            "benefits",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
    )
    op.alter_column("companies", "website", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "companies",
        "country",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "VIETNAM",
            "INDIA",
            "CHINA",
            "JAPAN",
            "SOUTH_KOREA",
            "SINGAPORE",
            "TAIWAN",
            "UNITED_STATES",
            "CANADA",
            "UNITED_KINGDOM",
            "GERMANY",
            "NETHERLANDS",
            "SWEDEN",
            "FRANCE",
            "IRELAND",
            "POLAND",
            "AUSTRALIA",
            "NEW_ZEALAND",
            name="countryenum",
        ),
        existing_nullable=True,
        postgresql_using="country::countryenum",
    )
    op.drop_index(
        op.f("idx_companies_embedding_hnsw"),
        table_name="companies",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(op.f("ix_companies_embedding_model"), table_name="companies")
    op.drop_index(op.f("ix_companies_embedding_version"), table_name="companies")
    op.drop_column("companies", "embedding_model")
    op.drop_column("companies", "embedding")
    op.drop_column("companies", "embedding_version")
    op.create_index("idx_job_skills_skill_id", "job_skills", ["skill_id"], unique=False)
    op.alter_column(
        "jobs",
        "min_salary",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "max_salary",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "source",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "ITVIEC", "TOPDEV", "ITJOBS", "VIETNAMWORKS", "FPTJOBS", name="crawlwebsite"
        ),
        existing_nullable=False,
        postgresql_using="source::crawlwebsite",
    )
    op.drop_index(
        op.f("idx_jobs_embedding_hnsw"),
        table_name="jobs",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(op.f("ix_jobs_embedding_model"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_embedding_version"), table_name="jobs")
    op.create_index(op.f("ix_jobs_source"), "jobs", ["source"], unique=False)
    op.drop_column("jobs", "embedding_model")
    op.drop_column("jobs", "embedding")
    op.drop_column("jobs", "embedding_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "embedding_version", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "jobs",
        sa.Column("embedding_model", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_jobs_source"), table_name="jobs")
    op.create_index(
        op.f("ix_jobs_embedding_version"), "jobs", ["embedding_version"], unique=False
    )
    op.create_index(
        op.f("ix_jobs_embedding_model"), "jobs", ["embedding_model"], unique=False
    )
    op.create_index(
        op.f("idx_jobs_embedding_hnsw"),
        "jobs",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.alter_column(
        "jobs",
        "source",
        existing_type=sa.Enum(
            "ITVIEC", "TOPDEV", "ITJOBS", "VIETNAMWORKS", "FPTJOBS", name="crawlwebsite"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "max_salary",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "min_salary",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_index("idx_job_skills_skill_id", table_name="job_skills")
    op.add_column(
        "companies",
        sa.Column(
            "embedding_version", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "companies",
        sa.Column("embedding_model", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_companies_embedding_version"),
        "companies",
        ["embedding_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_companies_embedding_model"),
        "companies",
        ["embedding_model"],
        unique=False,
    )
    op.create_index(
        op.f("idx_companies_embedding_hnsw"),
        "companies",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.alter_column(
        "companies",
        "country",
        existing_type=sa.Enum(
            "VIETNAM",
            "INDIA",
            "CHINA",
            "JAPAN",
            "SOUTH_KOREA",
            "SINGAPORE",
            "TAIWAN",
            "UNITED_STATES",
            "CANADA",
            "UNITED_KINGDOM",
            "GERMANY",
            "NETHERLANDS",
            "SWEDEN",
            "FRANCE",
            "IRELAND",
            "POLAND",
            "AUSTRALIA",
            "NEW_ZEALAND",
            name="countryenum",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column("companies", "website", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("companies", "benefits")
    op.create_table(
        "company_benefits",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("company_benefits_company_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("company_benefits_pkey")),
    )
    op.create_index(
        op.f("ix_company_benefits_company_id"),
        "company_benefits",
        ["company_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_curriculum_vitae_projects_cv_id"),
        table_name="curriculum_vitae_projects",
    )
    op.drop_table("curriculum_vitae_projects")
    op.drop_index(op.f("ix_job_embeddings_job_id"), table_name="job_embeddings")
    op.drop_index(
        op.f("ix_job_embeddings_embedding_model"), table_name="job_embeddings"
    )
    op.drop_index(
        "idx_job_embeddings_embedding_hnsw",
        table_name="job_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("job_embeddings")
    op.drop_index(
        op.f("ix_curriculum_vitaes_profile_id"), table_name="curriculum_vitaes"
    )
    op.drop_table("curriculum_vitaes")
    op.drop_index(
        op.f("ix_consultee_embeddings_profile_id"), table_name="consultee_embeddings"
    )
    op.drop_index(
        op.f("ix_consultee_embeddings_embedding_model"),
        table_name="consultee_embeddings",
    )
    op.drop_index(
        "idx_consultee_embeddings_embedding_hnsw",
        table_name="consultee_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("consultee_embeddings")
    op.drop_index(
        op.f("ix_consultee_profiles_user_id"), table_name="consultee_profiles"
    )
    op.drop_table("consultee_profiles")
    op.drop_index(
        op.f("ix_consultant_histories_user_id"), table_name="consultant_histories"
    )
    op.drop_index(
        op.f("ix_consultant_histories_consultant_mode"),
        table_name="consultant_histories",
    )
    op.drop_table("consultant_histories")
    op.drop_index(
        op.f("ix_company_embeddings_embedding_model"), table_name="company_embeddings"
    )
    op.drop_index(
        op.f("ix_company_embeddings_company_id"), table_name="company_embeddings"
    )
    op.drop_index(
        "idx_company_embeddings_embedding_hnsw",
        table_name="company_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("company_embeddings")
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.drop_index(op.f("ix_user_github_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###

    # Drop custom Enum types
    country_enum = postgresql.ENUM(name="countryenum")
    country_enum.drop(op.get_bind(), checkfirst=True)

    crawl_website_enum = postgresql.ENUM(name="crawlwebsite")
    crawl_website_enum.drop(op.get_bind(), checkfirst=True)

    consultant_mode_enum = postgresql.ENUM(name="consultantmode")
    consultant_mode_enum.drop(op.get_bind(), checkfirst=True)
