"""Fixing_one_to_many_company_table

Revision ID: 2e2f51650d34
Revises: b8dcbe9ba1a2
Create Date: 2026-07-25 07:40:59.334781

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2e2f51650d34"
down_revision: Union[str, Sequence[str], None] = "b8dcbe9ba1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
