"""Remove_unnecessary_company_fields

Revision ID: 582e7696c4df
Revises: 0be2d17fa0d4
Create Date: 2026-07-22 08:53:20.225127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "582e7696c4df"
down_revision: Union[str, Sequence[str], None] = "0be2d17fa0d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "mission")
    op.drop_column("companies", "rating")
    op.drop_column("companies", "vision")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("vision", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "companies",
        sa.Column("mission", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
