"""initiation_database_model

Revision ID: 807dce0cc12c
Revises:
Create Date: 2026-07-23 13:19:44.933463

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "807dce0cc12c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("industry", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slogan", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "company_type",
            sa.Enum(
                "PRODUCT",
                "OUTSOURCING",
                "CONSULTING",
                "AGENCY",
                "NON_PROFIT",
                "OTHER",
                name="companytype",
            ),
            nullable=True,
        ),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "addresses",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("working_days", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("overtime_policy", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("vector_context", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(
                sa.JSON(), "sqlite"
            ),
            nullable=True,
        ),
        sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("embedding_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_companies_embedding_hnsw",
        "companies",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_companies_company_type"), "companies", ["company_type"], unique=False
    )
    op.create_index(
        op.f("ix_companies_country"), "companies", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_companies_embedding_model"),
        "companies",
        ["embedding_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_companies_embedding_version"),
        "companies",
        ["embedding_version"],
        unique=False,
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=True)
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.create_table(
        "company_benefits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_benefits_company_id"),
        "company_benefits",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "job_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("expired_date", sa.DateTime(), nullable=False),
        sa.Column(
            "seniority",
            sa.Enum(
                "INTERN",
                "JUNIOR",
                "MID",
                "SENIOR",
                "LEAD",
                "MANAGER",
                "DIRECTOR",
                "EXECUTIVE",
                "UNKNOWN",
                name="senioritylevel",
            ),
            nullable=False,
        ),
        sa.Column("min_salary", sa.Float(), nullable=False),
        sa.Column("max_salary", sa.Float(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("VND", "USD", "EUR", "JPY", "SGD", name="currency"),
            nullable=False,
        ),
        sa.Column("working_hours", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "working_model",
            sa.Enum("ONSITE", "HYBRID", "REMOTE", "OTHER", name="workingmodel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "DRAFT", "EXPIRED", name="jobstatus"),
            nullable=True,
        ),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "responsibilities",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "required_qualifications",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "nice_to_have",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "domains",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("vector_context", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(
                sa.JSON(), "sqlite"
            ),
            nullable=True,
        ),
        sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("embedding_version", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "min_salary <= max_salary", name="check_min_salary_le_max_salary"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_jobs_embedding_hnsw",
        "jobs",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_jobs_company_id"), "jobs", ["company_id"], unique=False)
    op.create_index(op.f("ix_jobs_content_hash"), "jobs", ["content_hash"], unique=True)
    op.create_index(op.f("ix_jobs_currency"), "jobs", ["currency"], unique=False)
    op.create_index(
        op.f("ix_jobs_embedding_model"), "jobs", ["embedding_model"], unique=False
    )
    op.create_index(
        op.f("ix_jobs_embedding_version"), "jobs", ["embedding_version"], unique=False
    )
    op.create_index(op.f("ix_jobs_seniority"), "jobs", ["seniority"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_title"), "jobs", ["title"], unique=False)
    op.create_index(op.f("ix_jobs_url"), "jobs", ["url"], unique=True)
    op.create_index(
        op.f("ix_jobs_working_model"), "jobs", ["working_model"], unique=False
    )
    op.create_table(
        "job_skills",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "skill_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_skills")
    op.drop_index(op.f("ix_jobs_working_model"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_url"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_title"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_seniority"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_embedding_version"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_embedding_model"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_currency"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_content_hash"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_company_id"), table_name="jobs")
    op.drop_index(
        "idx_jobs_embedding_hnsw",
        table_name="jobs",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("jobs")
    op.drop_index(op.f("ix_company_benefits_company_id"), table_name="company_benefits")
    op.drop_table("company_benefits")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_embedding_version"), table_name="companies")
    op.drop_index(op.f("ix_companies_embedding_model"), table_name="companies")
    op.drop_index(op.f("ix_companies_country"), table_name="companies")
    op.drop_index(op.f("ix_companies_company_type"), table_name="companies")
    op.drop_index(
        "idx_companies_embedding_hnsw",
        table_name="companies",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("companies")
    # ### end Alembic commands ###
