"""Update user and consultee profile field

Revision ID: 92e578e0ee37
Revises: 9361e5e82c6b
Create Date: 2026-08-02 13:06:31.548835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92e578e0ee37"
down_revision: Union[str, Sequence[str], None] = "9361e5e82c6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "consultee_profiles", "first_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "consultee_profiles", "last_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "consultee_profiles", "birthday", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "consultee_profiles", "biography", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "consultee_profiles", "goal", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "consultee_profiles",
        "vector_context",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "consultee_profiles",
        "vector_context",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "consultee_profiles", "goal", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "consultee_profiles", "biography", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "consultee_profiles", "birthday", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "consultee_profiles", "last_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "consultee_profiles", "first_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
