"""Update skills and job relationship issuse

Revision ID: 9361e5e82c6b
Revises: 1023ca41535d
Create Date: 2026-08-01 11:23:40.427953

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9361e5e82c6b"
down_revision: str | Sequence[str] | None = "1023ca41535d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
