"""Update skills and job relationship issuse

Revision ID: 9361e5e82c6b
Revises: 1023ca41535d
Create Date: 2026-08-01 11:23:40.427953

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9361e5e82c6b"
down_revision: Union[str, Sequence[str], None] = "1023ca41535d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
