"""Add FRESHER to SeniorityLevel enum

Revision ID: b8dcbe9ba1a2
Revises: 807dce0cc12c
Create Date: 2026-07-24 15:18:32.694921

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8dcbe9ba1a2"
down_revision: str | Sequence[str] | None = "807dce0cc12c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adding 'FRESHER' value to PostgreSQL senioritylevel enum type
    op.execute("ALTER TYPE senioritylevel ADD VALUE 'FRESHER'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
