name: Labels

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - opened
      - synchronize
      - reopened

      - labeled
      - unlabeled

permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout Code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled' }}

    - name: Labeler pull request
      uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
      if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled' }}

    - name: Label Release/Tag based on Commits
      if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: bash scripts/release/label-release-tag.sh

    - run: echo "Done adding labels"

  check-labels:
    needs:
      - labeler
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: agilepathway/label-checker@c3d16ad512e7cea5961df85ff2486bb774caf3c5 # v1.6.65
        with:
          any_of: "Type: Documentation,Type: Maintenance,Type: Enhancement, Type: Release - Tag"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
